# Generated by Django 5.1.2 on 2024-10-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plans",
            name="subscription_required",
            field=models.BooleanField(default=True),
        ),
    ]
