# Generated by Django 5.1.2 on 2024-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_alter_plans_subscription_required"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="monthly_price",
            new_name="price",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="days",
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
