# Generated by Django 5.1.2 on 2024-10-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_rename_monthly_price_subscriptionplan_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
            ),
        ),
    ]
