# Generated by Django 5.1.2 on 2024-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_usersubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=10,
            ),
        ),
    ]
